env:
  browser: true
  es2021: true
  node: true
  mocha: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "linebreak-style": 0,
  "indent": ["error", 2]
}
settings: {
  'import/resolver': {
    node: {
      extensions: [ 'ts' ], 
      paths: [ 'src' ]
    }
  }
}
  