env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
  project: [ "./tsconfig.json", './tsconfig.test.json' ]
plugins:
  - '@typescript-eslint'
rules: {
  "linebreak-style": 0,
  "indent": ["error", 2], 
  "no-console": ["error", { allow: ["warn", "error", "log"] }]
}
