env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - react-hooks
rules: {
  "linebreak-style": 0,
  "indent": ["error", 2], 
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/exhaustive-deps": "warn",
  "react/jsx-filename-extension": [2, 
    { extensions: ['.js', '.jsx', '.ts', '.tsx'] }
  ],
  "react/function-component-definition": [2, { 
      namedComponents: "arrow-function",
      unnamedComponents: "arrow-function"
    }
  ],
  "arrow-body-style": ["error", "always"],
  "import/extensions": [2, "never" ]
}
settings: {
  "import/parsers": {
    "@typescript-eslint/parser": [".ts", ".tsx"]
  },
  "import/resolver": {
    "typescript": {
      "alwaysTryTypes": true,
      "project": "./"
    }
  }
}