apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-admin-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: k8s-admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-admin-role
