apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    name: elasticsearch
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
      protocol: TCP
