apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    name: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP
