apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    name: rabbitmq
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: {{ .Values.rabbitmq:port }}
      protocol: TCP
