version: "3.9"
services:
  redis-server: 
    image: redis
    ports:
      - "6379:6379"
  mongo-server:
    image: mongo
    ports: 
      - "27017:27017"
  es-server:
    image: elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  web:
    build: .
    ports:
      - "1330:1330"
  