version: "3.9"
services:
  redis-server: 
    image: redis
    ports:
      - "6379:6379"
  mongo-server:
    image: mongo
    ports: 
      - "27017:27017"
  web:
    build: .
    ports:
      - "3000:3000"
  