namespace: default

redis:
  image: redis
  replicaCount: 2
  port: 6379
  url: redis://redis.default.svc.cluster.local:6379

mongo:
  image: mongo
  replicaCount: 2
  port: 27017
  url: mongodb://mongo.default.svc.cluster.local:27017

rabbitmq:
  image: rabbitmq
  replicaCount: 1
  port: 5672
  url: amqp://rabbitmq.default.svc.cluster.local:5672

chartapi:
  image: chartapi #custom image
  pullPolicy: Always
  replicaCount: 2
  port: 1330
  redisUrl: redis://redis.default.svc.cluster.local:6379
  mqUrl: amqp://rabbitmq.default.svc.cluster.local:5672

portapi:
  image: portapi #custom image
  pullPolicy: Always
  replicaCount: 1
  port: 3000
  mongoUrl: mongodb://mongo.default.svc.cluster.local:27017

tracker:
  image: tracker #custom image
  pullPolicy: Always
  replicaCount: 2
  port: 1333
  trackReqName: "track_stock_register"
  emitterName: "trady_tracker_event"
  refUrl: "https://insert-ref.com"
  apiKey: "dummy-key"
  healthUrl: "0.0.0.0:1333"
