apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-admin-rolebinding
  namespace: default
  uid: 87dba465-51b7-405a-b5ed-1b140a915857
  resourceVersion: '4756'
  creationTimestamp: '2022-12-04T13:06:28Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"k8s-admin-rolebinding","namespace":"default"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"k8s-admin-role"},"subjects":[{"kind":"User","name":"k8s-admin-user"}]}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-12-04T13:06:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:roleRef: {}
        f:subjects: {}
  selfLink: >-
    /apis/rbac.authorization.k8s.io/v1/namespaces/default/rolebindings/k8s-admin-rolebinding
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: k8s-admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-admin-role
