apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-admin-role
  namespace: default
  uid: 0cd14e36-5a65-48a9-ab53-e495859a435e
  resourceVersion: '4461'
  creationTimestamp: '2022-12-04T13:04:38Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"k8s-admin-role","namespace":"default"},"rules":[{"apiGroups":["","apps","batch","extensions"],"resources":["configmaps","cronjobs","deployments","events","ingresses","jobs","pods","pods/attach","pods/exec","pods/log","pods/portforward","secrets","services"],"verbs":["create","delete","describe","get","list","patch","update"]}]}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-12-04T13:04:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:rules: {}
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/roles/k8s-admin-role
rules:
  - verbs:
      - create
      - delete
      - describe
      - get
      - list
      - patch
      - update
    apiGroups:
      - ''
      - apps
      - batch
      - extensions
    resources:
      - configmaps
      - cronjobs
      - deployments
      - events
      - ingresses
      - jobs
      - pods
      - pods/attach
      - pods/exec
      - pods/log
      - pods/portforward
      - secrets
      - services
