namespace: default

# FIXME: generate url based on namespace and port

redis:
  image: redis:latest
  replicaCount: 2
  port: 6379
  url: redis://redis.default.svc.cluster.local:6379

mongo:
  image: mongo:latest
  replicaCount: 2
  port: 27017
  url: mongodb://mongo.default.svc.cluster.local:27017

elasticsearch:
  image: elasticsearch:latest
  replicaCount: 2
  port: 9200
  url: es://elasticsearch.default.svc.cluster.local:9200

rabbitmq:
  image: rabbitmq
  replicaCount: 1
  port: 5672
  url: amqp://rabbitmq.default.svc.cluster.local:5672

stock-tracker:
  image: innfi/stock-tracker:latest
  pullPolicy: Always
  replicaCount: 1
  port: 1333
  trackReqName: "track_stock_register"
  emitterName: "trady_tracker_event"
  refUrl: "https://insert-ref.com"
  apiKey: "dummy-key"
  healthUrl: "0.0.0.0:1333"
