version: "3"
services:
  redis-server:
    image: redis
    volumes:
      - ./redis_server.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - elastic

  rabbitmq-server:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - elastic

  mongo-server:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - elastic

  es01:
    image: elasticsearch:7.17.6
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  es02:
    image: elasticsearch:7.17.6
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9301:9300
    networks:
      - elastic

  es03:
    image: elasticsearch:7.17.6
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9302:9300
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:7.17.6
    depends_on:
      - es01
      - es02
      - es03
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - elastic
  
  chart-api:
    image: innfi/trady-chart:latest
    depends_on:
      - redis-server
      - es01
    environment:
      - PORT=1330
      - REDIS_URL=redis://127.0.0.1:6379
      - MQ_URL=amqp://127.0.0.1:5672
      - ES_URL=http://127.0.0.1:9200
    ports:
      - "1330:1330"
    
  # port-api:
  #   image: innfi/trady-port:0.0.1
  #   depends_on:
  #     - rabbitmq-server
  #     - mongo-server
  #     - es-server
  #   environment:
  #     - PORT_QUEUE=port_queue
  #     - MQ_URL=amqp://rabbitmq-server:5672
  #     - ES_URL=es://es-server:9200
  #     - MONGO_URL=mongodb://mongo-server:27017
  #   ports:
  #     - "3000:3000"

  # stock-tracker:
  #   image: innfi/stock-tracker:0.0.1
  #   depends_on:
  #     - redis-server
  #     - rabbitmq-server
  #   environment:
  #     - MODE=PROD
  #     - REDIS_URL=redis://redis-server:6379
  #     - MQ_URL=amqp://rabbitmq-server:5672
  #     - TRACK_REQ_NAME=track_stock_register
  #     - EMITTER_NAME=trady_tracker_event
  #     - REF_URL=https://insert-ref.com
  #     - API_KEY=dummy-key
  #     - HEALTH_URL=0.0.0.0:1333
  #   ports:
  #     - "1333:1333"

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  kibana:
    driver: local

networks:
  elastic:
    driver: bridge
