version: "3"
services:
  redis-server:
    image: redis
    volumes:
      - ./redis_server.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq-server:
    image: rabbitmq
    ports:
      - "5672:5672"

  stock-tracker:
    image: innfi/stock-tracker:0.0.1
    depends_on:
      - redis-server
      - rabbitmq-server
    environment:
      - MODE=PROD
      - REDIS_URL=redis://redis-server:6379
      - MQ_URL=amqp://rabbitmq-server:5672
      - TRACK_REQ_NAME=track_stock_register
      - EMITTER_NAME=trady_tracker_event
      - REF_URL=https://insert-ref.com
      - API_KEY=dummy-key
      - HEALTH_URL=0.0.0.0:1333
    ports:
      - "1333:1333"
