version: "3"
services:
  redis-server:
    image: redis
    volumes:
      - ./redis_server.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq-server:
    image: rabbitmq
    ports:
      - "5672:5672"

  mongo-server:
    image: mongo
    ports:
      - "27017:27017"

  # es01:
  #   image: elasticsearch:7.17.6
  #   container_name: es01
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es02,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data01:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   networks:
  #     - elastic

  # es02:
  #   image: elasticsearch:7.17.6
  #   container_name: es02
  #   environment:
  #     - node.name=es02
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data02:/usr/share/elasticsearch/data
  #   ports:
  #     - 9301:9300
  #   networks:
  #     - elastic

  # es03:
  #   image: elasticsearch:7.17.6
  #   container_name: es03
  #   environment:
  #     - node.name=es03
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es02
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data03:/usr/share/elasticsearch/data
  #   ports:
  #     - 9302:9300
  #   networks:
  #     - elastic

  # logstash:
  #   image: logstash:7.17.6
  #   container_name: logstash
  #   depends_on:
  #     - es01
  #     - es02
  #     - es03
  #   environment:
  #     - "xpack.monitoring.enabled=false"
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "ELASTICSEARCH_HOST=es01:9200"
  #   volumes:
  #     - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #   ports:
  #     - "5044:5044"
  #     - "50000:50000/tcp"
  #     - "50000:50000/udp"
  #     - "9600:9600"
  #   networks:
  #      - elastic

  # kibana:
  #   container_name: kibana
  #   image: kibana:7.17.6
  #   depends_on:
  #     - es01
  #     - es02
  #     - es03
  #   environment:
  #     SERVER_NAME: kibana
  #     ELASTICSEARCH_HOSTS: http://es01:9200
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - elastic

# volumes:
#   data01:
#     driver: local
#   data02:
#     driver: local
#   data03:
#     driver: local
#   kibana:
#     driver: local

# networks:
#   elastic:
#     driver: bridge

# wsl -d docker-desktop
# sysctl -w vm.max_map_count=262144