version: "3"
services:
  redis-server:
    image: redis
    volumes:
      - ./redis_server.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq-server:
    image: rabbitmq
    ports:
      - "5672:5672"

  mongo-server:
    image: mongo
    ports:
      - "27017:27017"

  es-server1:
    image: elasticsearch
    container_name: es01
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xms512m"
    volumes:
      - ./elasticsearch/data01:/usr/share/elasticsearch/data

  es-server2:
    image: elasticsearch
    container_name: es02
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xms512m"
    volumes:
      - ./elasticsearch/data02:/usr/share/elasticsearch/data

  stock-tracker:
    image: innfi/stock-tracker:0.0.1
    depends_on:
      - redis-server
      - rabbitmq-server
    environment:
      - MODE=PROD
      - REDIS_URL=redis://redis-server:6379
      - MQ_URL=amqp://rabbitmq-server:5672
      - TRACK_REQ_NAME=track_stock_register
      - EMITTER_NAME=trady_tracker_event
      - REF_URL=https://insert-ref.com
      - API_KEY=dummy-key
      - HEALTH_URL=0.0.0.0:1333
    ports:
      - "1333:1333"

  chart-api:
    image: innfi/trady-chart:latest
    depends_on:
      - redis-server
      - es-server
    environment:
      - PORT=1330
      - REDIS_URL=redis://redis-server:6379
      - MQ_URL=amqp://rabbitmq-server:5672
      - ES_URL=es://es-server:9200
    ports:
      - "1330:1330"
    
  port-api:
    image: innfi/trady-port:latest
    depends_on:
      - rabbitmq-server
      - mongo-server
      - es-server
    environment:
      - PORT_QUEUE=port_queue
      - MQ_URL=amqp://rabbitmq-server:5672
      - ES_URL=es://es-server:9200
      - MONGO_URL=mongodb://mongo-server:27017
    ports:
      - "3000:3000"