apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartapi
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.chartapi.replicaCount }}
  selector:
    matchLabels:
      name: chartapi
  template:
    metadata:
      labels:
        name: chartapi
    spec:
      containers:
      - name: chartapi
        image: {{ .Values.chartapi.image }}
        imagePullPolicy: {{ .Values.chartapi.pullPolicy }}
        env:
        - name: REDIS_URL
          value: {{ .Values.redis.url }}
        - name: MQ_URL
          value: {{ .Values.rabbitmq.url }}
        ports:
        - containerPort: {{ .Values.chartapi.port }}
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 400Mi
      imagePullSecrets:
        - name: regcred