apiVersion: v1
kind: Service
metadata:
  name: chartapi
  namespace: {{ .Values.namespace }}
spec:
  selector:
    name: chartapi
  type: LoadBalancer
  ports:
  - port: {{ .Values.chartapi.port }}
    targetPort: {{ .Values.chartapi.port }}
    protocol: TCP
