apiVersion: v1
kind: Service
metadata:
  name: tracker
  namespace: {{ .Values.namespace }}
spec:
  selector:
    name: tracker
  type: LoadBalancer
  ports:
  - port: {{ .Values.tracker.port }}
    targetPort: {{ .Values.tracker.port }}
    protocol: TCP
