[package]
name = "stock_tracker"
version = "0.1.0"
authors = ["innfi"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "stock_tracker"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }
