name: action.stock
on:
  push:
    branches:
      - main
    paths:
      - "stock-tracker/**"
      - .github/workflows/action.stock.yaml

defaults:
  run:
    working-directory: ./stock-tracker

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./stock-tracker
      - name: test
        run: cargo test