name: action.port
on:
  push:
    branches:
      - port/release
    paths:
      - "port-api/**"
      - .github/workflows/action.port.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./port-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: module caching
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: | 
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      
      - name: dependencies
        run: npm install

      - name: lint
        run: npm run lint

      # - name: test
      #   run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./port-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./port-api
          file: ./port-api/Dockerfile
          push: true
          tags: docker.io/innfi/trady-port:latest
