name: action.stock
on:
  push:
    branches:
      - stock/release
    paths:
      - "stock-tracker/**"
      - .github/workflows/action.stock.yaml

defaults:
  run:
    working-directory: ./stock-tracker

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./stock-tracker
      - name: test
        run: cargo test

  push:
    needs: test
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./stock-tracker
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./stock-tracker
          file: ./stock-tracker/Dockerfile
          push: true
          tags: docker.io/innfi/stock-tracker:latest
